site_name: YACSPanel Guide
site_url: https://example.com/
repo_url: https://github.com/
theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.sections

nav:
  - üëã –í—Å—Ç—É–ø–ª–µ–Ω–∏–µ: index.md
  - üëæ –§—É–Ω–∫—Ü–∏–æ–Ω–∞–ª YACSPanel: functional.md
  - ‚öôÔ∏è –ù–∞—Å—Ç—Ä–æ–π–∫–∞ –∏ –∫–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏—è:
    - –£—Å—Ç–∞–Ω–æ–≤–∫–∞ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ–≥–æ –ü–û –∏ –Ω–∞—Å—Ç—Ä–æ–π–∫–∞ —Å–∏—Å—Ç–µ–º—ã: setup/software.md
    - –£—Å—Ç–∞–Ω–æ–≤–∫–∞ –∏ –Ω–∞—Å—Ç—Ä–æ–π–∫–∞ YACSPanel: setup/install.md
  - ‚≠ê –î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–µ –Ω–∞—Å—Ç—Ä–æ–π–∫–∏:
    - –ù–∞—Å—Ç—Ä–æ–π–∫–∞ —Ñ–æ–Ω–æ–≤–æ–≥–æ —Ñ–∞—Ä–º–∞: optional/background.md
    - –§–∞—Ä–º –Ω–µ—Å–∫–æ–ª—å–∫–∏—Ö –ø–∞—á–µ–∫: optional/multi_batch.md
  - ‚å®Ô∏è –†–∞–±–æ—Ç–∞ —Å –ø–∞–Ω–µ–ª—å—é:
    - –†–µ–∂–∏–º—ã —Ñ–∞—Ä–º–∞: working/modes.md
    - –ó–∞–ø—É—Å–∫ Wingman 2x2: working/wingman.md
    - –ó–∞–ø—É—Å–∫ 5x5 Simulation: working/simulation.md
    - –ó–∞–ø—É—Å–∫ 5x5 Classic: working/classic.md
    - –ü–æ–ª—É–∞–≤—Ç–æ–º–∞—Ç Vertigo: working/vertigo.md
    - üíµ –§–ê–†–ú –ë–ü (Armory Pass): working/armory.md
  - –ú–æ–¥—É–ª—å ‚ö°Activity booster: activity_booster.md
  - üíπ –î–µ—Ç–∞–ª—å–Ω—ã–π —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª:
    - –û–ø–∏—Å–∞–Ω–∏–µ –∫–Ω–æ–ø–æ–∫: features/buttons.md
    - –ù–∞—Å—Ç—Ä–æ–π–∫–∏ settings.json: features/settings_json.md
  - ‚ö†Ô∏è –†–µ—à–µ–Ω–∏–µ –ø—Ä–æ–±–ª–µ–º | FAQ:
    - –†–µ—à–µ–Ω–∏–µ –ø—Ä–æ–±–ª–µ–º: faq/troubleshooting.md

